version: '3.6'
services:
  boiler:
    build: .
    volumes:
      - type: bind
        source: .
        target: /opt/boiler/
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - WORKERS=4
      - WSGI_TIMEOUT=10
      - RELOAD=true
    ports:
      - '8000:8000'
